---
title: "Feature Analysis"
author: "Team Market Research"
date: "June 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Setting up tables features:


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(DT)
library(RColorBrewer)
library(htmlwidgets)
library(knitr)

massive_score <- readRDS("massive_score.rds")

datasets <- list()

for(i in c("Must have","Ideal","Could live without")){
  sub_df <- massive_score %>%
    filter(`Final Requirement Level` == i) %>%
    mutate(Feature = ifelse(`Feature Present Value` == "FALSE", NA,
                            as.numeric(`Satisfaction Value`))) %>%
    group_by(vender, Category) %>%
    summarise(count = sum(Feature, na.rm = TRUE)/sum(!is.na(Feature))) %>%
    spread(Category, count) %>%
      mutate(requirement = i)
  
  datasets[[i]] <- sub_df
    
}

htmltools::tagList(
  lapply(datasets, function(x) {
    datatable(x[,-ncol(x)],  extensions = 'Buttons',
              caption = htmltools::tags$caption(
    style = 'text-align: center; font-weight: bold; font-size: 200%',
    htmltools::h1(unique(x[ncol(x)]))),
        options = list(#dom = 'ft',
            dom = 'Bfrtip',
            pageLength = nrow(x),
            buttons =
              list('colvis', list(
                extend = 'collection',
                buttons = list(list(extend='csv',
                                    filename = 'featurePresent'),
                               list(extend='excel',
                                    filename = 'featurePresent'),
                               list(extend='pdf',
                                    filename= 'featurePresent')),
                text = 'Download'
                )
              )))
    })
)
```



