---
title: "Feature Available Analysis"
author: "Team Market Research"
date: "June 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Setting up tables for each vendor. First we'll only look at MUST HAVES:


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(DT)
library(RColorBrewer)
library(htmlwidgets)
library(knitr)

massive_score <- readRDS("massive_score.rds")
massive_score <- filter(massive_score, `Final Requirement Level` == "Must have")

datasets <- list()

for(i in unique(massive_score$vender)){
  sub_df <- filter(massive_score, vender == i) %>%
    select(Category,`Feature Present`,vender,`Feature Present Value`) %>%
    mutate(Feature = ifelse(`Feature Present Value` == "FALSE", NA,
                            as.numeric(`Feature Present Value`))) %>%
    group_by(Category,`Feature Present`,vender) %>%
    summarize(counts = sum(Feature, na.rm = TRUE) / sum(!is.na(Feature))) %>%
    spread(`Feature Present`,counts) 
  
  datasets[[i]] <- sub_df
    
}

htmltools::tagList(
  lapply(datasets, function(x) {
    datatable(x[,-2],  extensions = 'Buttons',
              caption = htmltools::tags$caption(
    style = 'text-align: center; font-weight: bold; font-size: 200%',
    htmltools::h1(unique(x$vender))),
    options = list(#dom = 'ft',
            dom = 'Bfrtip',
            buttons =
              list('colvis', list(
                extend = 'collection',
                buttons = list(list(extend='csv',
                                    filename = 'gapAnalysis'),
                               list(extend='excel',
                                    filename = 'gapAnalysis'),
                               list(extend='pdf',
                                    filename= 'gapAnalysis')),
                text = 'Download'
                )
              )))
    })
)
```



